package com.bficara.takehome_be.Init;

import jakarta.annotation.PostConstruct;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

@Service
public class H2DataBaseInitializer {
    public final JdbcTemplate jdbcTemplate;

    public H2DataBaseInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @PostConstruct
    public void initializeDb() {

        String sql =
        "CREATE TABLE IF NOT EXISTS CAR(\n" +
        "\n" +
        "                                  \"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
        "\n" +
        "                                  \"CARYEAR\" INTEGER,\n" +
        "\n" +
        "                                  \"MSRP\" DECIMAL(10, 2),\n" +
        "\n" +
        "                                  \"MAKE\" CHARACTER VARYING(50),\n" +
        "\n" +
        "                                  \"MODEL\" CHARACTER VARYING(50)\n" +
        "\n" +
        ");\n" +
        "ALTER TABLE \"PUBLIC\".\"CAR\" ADD CONSTRAINT IF NOT EXISTS \"PUBLIC\".\"CONSTRAINT_1\" PRIMARY KEY(\"ID\");\n" +
        "\n";

        jdbcTemplate.execute(sql);

        String dataExists = "SELECT 1 FROM CAR LIMIT 1";
        boolean dataAlreadyExists;
        try {
            jdbcTemplate.queryForObject(dataExists, Integer.class);
            dataAlreadyExists = true;
            System.out.println("data exists");
        } catch (EmptyResultDataAccessException e) {
            System.out.println("data not exists");
            dataAlreadyExists = false;
        }

        if (!dataAlreadyExists) {

            String insert =
                    "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2018, 45000.00, 'acura', 'mdx');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2017, 27500.00, 'ford', 'focus');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2017, 33000.00, 'chevrolet', 'impala');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2018, 40000.00, 'chrysler', 'pacifica');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2018, 55000.00, 'jeep', 'wrangler');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2017, 28000.00, 'honda', 'accord');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2019, 50000.00, 'infinity', 'g35');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2019, 6000.00, 'chevrolet', 'avalanche');\n" +
                            "INSERT INTO CAR (CARYEAR, MSRP, MAKE, MODEL) VALUES (2017, 30000.00, 'nissan', 'altima');\n";

            jdbcTemplate.execute(insert);
        }
    }

}
